# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: community
name: sap_libs
version: 1.0.0
readme: README.md
authors:
  - Rainer Leber (github.com/rainerleber)
  - Robert Kraemer (github.com/rkpobe)
description: SAP Module community collection for Ansible
license_file: LICENSE
tags:
  - sap
repository: https://github.com/ansible-collections/community.sap
documentation: https://github.com/ansible-collection/community.sap
homepage: https://github.com/ansible-collections/community.sap
issues: https://github.com/ansible-collections/community.sap/issues
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml