# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: community
name: sap_libs
version: 1.4.1
readme: README.md
authors:
  - Rainer Leber (github.com/rainerleber)
  - Robert Kraemer (github.com/rkpobe)
  - Sean Freeman (github.com/sean-freeman)
description: SAP Module community collection for Ansible
license_file: LICENSE
tags:
  - sap
repository: https://github.com/sap-linuxlab/community.sap_libs
documentation: https://github.com/sap-linuxlab/community.sap_libs
homepage: https://github.com/sap-linuxlab/community.sap_libs
issues: https://github.com/sap-linuxlab/community.sap_libs
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml